database:
    driver: pdo_mysql
    host: localhost
    database: database
    user: user
    password:
    default_language: pt_br

security:
    token:

elasticSearch:
    url: "http://leonardorifeli.com:9200"
