routes:
  crawler_github_repositories:
    pattern:  /github/repositories
    controller: App\Bundle\Crawler\Controller\GithubRepositoryController::indexAction
    requirements:
      _method:  GET

  crawler_github_sync:
    pattern:  /github/{token}/sync
    controller: App\Bundle\Crawler\Controller\GithubSyncController::startSync
    requirements:
      _method:  GET

  elasticSearch_sync:
    pattern: /elastic-search/{token}/index
    controller: App\Bundle\ElasticSearch\Controller\ElasticSearchSyncController;
    requirements:
      _method: GET
